### ISSUE TITLE
HBO Portugal not working.

### ISSUE THREAD

**Issue by ntilagoa** [arvvoid/plugin.video.hbogoeu#11] opened 2019-02-23 14:48 UTC
* [ ] Are you running the latest version?
Yes
**Describe the bug**
After login , just give error and do not enter plugin.

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [X ] Android

**Additional informatin on the environment**

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

**Additional context**

**Comment by arvvoid** [comment] 2019-02-24 08:30
Found the problem, silent device registration fails becouse the api call url is not correct for Portugal. Have to find the correct url for Portugla. After i find it and fix the addon should work.

I added support for Portugal recently have no way of testing it so atm is completly untested.

**Comment by arvvoid** [comment] 2019-02-24 20:04
Please test version: [plugin.video.hbogoeu-2.0.4~beta12.zip](https://github.com/arvvoid/repository.arvvoid/raw/master/plugin.video.hbogoeu/plugin.video.hbogoeu-2.0.4~beta12.zip) and report results with full debug log

**Comment by ntilagoa** [comment] 2019-02-24 21:04
Hi
Now do not give error and past the login screen but only shows search and favorites buttons, nothing else.
Log:
[LOG REMOVED CONTAINS BANNED ADD-ONS arvvoid]

**Comment by arvvoid** [comment] 2019-02-24 21:39
Hello,

please clean your installation from any banned add-on (per kodi forum rules [banned addons](https://kodi.wiki/view/banned%20addons) ).

Then provide a full Debug log (the one posted previously is not useful because it have debugging turned off), instructions: [Log_file/Easy](https://kodi.wiki/view/Log_file/Easy)

**Comment by ntilagoa** [comment] 2019-02-24 22:00
Sorry for that. Here it is:
https://paste.kodi.tv/iguyuneqaq

**Comment by arvvoid** [comment] 2019-02-25 08:12
It looks like Group listing api call for portugal return sucess with an empty list, so will have to find an alternative way to retrive the groups for Portugal.

In the meantime if you try to search does it work? If it does can you play someting from the search result? Does the favorite group work and list items in it?
Can you try to perform all this actions and send a debug log?

**Comment by ntilagoa** [comment] 2019-02-25 09:50
Hi Arvvoid
Favorites show up and play just fine.
Search do not work. Every time I try to search anything Kodi just quit.

**Comment by arvvoid** [comment] 2019-02-25 09:58
Ok if playback from favorites works that's promising.
Can you provide me a full debug log after the crash when you try to search in the add-on? So I can investigate that as well and fix it.

I found an alternative group listing method. Probably will be able to make a fix quickly.

**Comment by ntilagoa** [comment] 2019-02-25 10:25
Hi
After restart Kodi it seems that search is working.
I try 2, 3 searches and work ok and play fine from the found items.
Thank you very much for your work on this.

**Comment by arvvoid** [comment] 2019-02-25 20:42
Please test: [plugin.video.hbogoeu-2.0.5~beta13.zip](https://github.com/arvvoid/repository.arvvoid/raw/master/plugin.video.hbogoeu/plugin.video.hbogoeu-2.0.5~beta13.zip)

**Comment by ntilagoa** [comment] 2019-02-25 20:57
Hello
Ok. Now it shows: search, my list, home and series buttons, but not movies
Later try to upload log.

**Comment by arvvoid** [comment] 2019-02-25 21:35
I see the position if off by 1, i know what the problem is, will fix it tomorow

**Comment by arvvoid** [comment] 2019-02-26 08:13
Try: [plugin.video.hbogoeu-2.0.5.beta14.zip](https://github.com/arvvoid/plugin.video.hbogoeu/releases/download/2.0.5-beta14/plugin.video.hbogoeu-2.0.5.beta14.zip)

**Comment by ntilagoa** [comment] 2019-02-26 08:51
It is working ok. :)

On main screen “trending now” appears twice.
I have to go to work now. Later will try with more time and report back.
Thank you.

**Comment by arvvoid** [comment] 2019-02-26 10:35
Try: [plugin.video.hbogoeu-2.0.5~beta16.zip](https://github.com/arvvoid/repository.arvvoid/raw/master/plugin.video.hbogoeu/plugin.video.hbogoeu-2.0.5~beta16.zip) this one should solve that minor issue

**Comment by arvvoid** [comment] 2019-02-27 10:35
Solved closing

**Closed as completed by arvvoid** 2019-02-27 10:35 UTC
Labels: bug

**Comment by arvvoid** [comment] 2019-10-28 12:46
@all-contributors please add @ntilagoa for bug
