### ISSUE TITLE
[BUG] Spain/Nordic region: sometimes Non-English subtitles dosen't show right on specific languages.

### ISSUE THREAD

**Issue by rocknrollnor** [arvvoid/plugin.video.hbogoeu#157] opened 2020-04-24 20:37 UTC
![screenshot-kodi](https://user-images.githubusercontent.com/64284359/80254479-8a714580-867b-11ea-8530-4c74aeb02e4f.png)

The English subtitle works fine, can't find anything about it in the debug log.

Using Libre-Elec - x86

Thanks.

**Comment by arvvoid** [comment] 2020-04-25 10:37
Hello @rocknrollnor , without a full debug log in don t have enough info to answer this. Subtitles have been extensively tested and worked on all tested content. Also, the way subtitles are processed depends on the region.
Did you also make a comparison with the official client for the same show/episode time frame?

What follows is not only directed at you but anyone reporting an issue because I'm getting tired of having to explain the same thing most of the time, and ask additionally for logs most of the time when what is required when reporting an issue is clearly stated.
Full unedited and uncut debug logs are always required for a good reason, if a user reporting an issue has the skill and experience necessary to read a log correctly and arbitrarily decide if the log is useful or not then probably has the skill, expertise, and experience(regarding the add-on) necessary to fix the problem in the first place and can provide a fix directly instead of reporting the issue.

**Comment by rocknrollnor** [comment] 2020-04-26 08:58
Hi! 
Note taken about the log.

Tested again today. Some series/movies works, others don't. All good in the official client.
The srt-files to this episodes/movies has wrong/missing timestamps contra the ttml-files.

[kodi.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/4535390/kodi.log)

**Comment by arvvoid** [comment] 2020-04-27 06:55
Hello,
ok, so the problem is some ttml files for the Spain/Nordic region don't get converted correctly by the ttml2srt converter.
I will investigate, have to find out what the problem is with those files. Can you please provide what s the exact show, episode, and time frame where it happens.

**Comment by rocknrollnor** [comment] 2020-04-27 09:27
For example "Phil Spector" movie, at 02:07 or "1992" S01E01 at 01:26.

**Comment by arvvoid** [comment] 2020-04-27 10:05
Progress regarding this issue can be followed on pull request #158 , please test the test version published there and report back with debug logs.

**Comment by rocknrollnor** [comment] 2020-04-27 10:42
[kodi.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/4539095/kodi.log)

**Comment by arvvoid** [comment] 2020-04-27 11:20
@rocknrollnor does the problem persist with the test version in the pull request?

EDIT: nevermind I see in the log that it fails. I Will let you know when a new test version is ready. Unfortunately, I don't have access to the region in question so I can't test directly can only rely on sent logs to debug the changes.

**Comment by rocknrollnor** [comment] 2020-04-27 13:07
No problem, I can do that. Thank you for your time.

**Comment by arvvoid** [comment] 2020-04-29 08:15
Fixed in #158

**Comment by arvvoid** [comment] 2020-04-29 08:16
@all-contributors please add @rocknrollnor for bug

**Comment by arvvoid** [comment] 2020-04-30 08:52
Fixed and release in https://github.com/arvvoid/plugin.video.hbogoeu/releases/tag/2.6.0

**Closed as completed by arvvoid** 2020-04-30 08:52 UTC
Labels: bug, FIXED
