### ISSUE TITLE
Error with special characters in Win10 user name

### ISSUE THREAD

**Issue by petakpa1** [arvvoid/plugin.video.hbogoeu#146] opened 2020-04-13 18:34 UTC
I run the latest version of the addon on Kodi x86 v18.4 on a W10 x64 system 

The addon start, but when I want to play a movie I receive error message and the movie does not start.

Here is my Kodi log: https://paste.kodi.tv/olerululer.kodi

**Comment by arvvoid** [comment] 2020-04-13 19:11
`Log level changed to "LOG_LEVEL_NORMAL"`

Hello, @petakpa1 you didn’t enable debug logging in Kodi, the step is mentioned and describe in instructions. Please enable debug logging and post a new log.

**Comment by petakpa1** [comment] 2020-04-13 19:39
Hi Arvvoid,
Here is my full log: https://paste.kodi.tv/kegedajilo.kodi

Please note that I have a similar special characters related issue with Netflix addon prepared by CastagnaIT, but he finally succesfully solved it.

Unfortunately I am not sure whether HBOGOEU addon worked or not before I installed Netflix addon... If you need I can send you the beta version of Netflix currently used by me.

**Comment by arvvoid** [comment] 2020-04-13 20:32
@petakpa1 no need this is enough to confirm the issue and see what is affected. Well special chars there where not taken into account and i didn’t test for that.
Even if some os allow that is not really common and best practice.
A fix is possible and not complicated but will take some time, require a fix in multiple places and testing then on both Kodi 18 and 19 (on kodi 19 things might work as they are but is in alpha so would not recomend for normal use at this time).

Will post here when a fix is ready for testing.

**Comment by petakpa1** [comment] 2020-04-13 20:52
Ok. Thank you very much for trying to solve it. If you send me beta version I can test it on my Win10 system.

**Comment by arvvoid** [comment] 2020-04-14 17:41
Fixed in #147

**Comment by arvvoid** [comment] 2020-04-14 20:30
@all-contributors please add @petakpa1 for bug

**Comment by arvvoid** [comment] 2020-04-16 11:57
The issue is fixed and merged in master, will close this issue when I make a new release.

**Comment by arvvoid** [comment] 2020-04-17 20:42
Fix released in https://github.com/arvvoid/plugin.video.hbogoeu/releases/tag/2.5.8 published in Kodi add-on repository

**Closed as completed by arvvoid** 2020-04-17 20:42 UTC
Labels: bug, FIXED
