### ISSUE TITLE
[BUG] Searching problem

### ISSUE THREAD

**Issue by Klown1985** [arvvoid/plugin.video.hbogoeu#125] opened 2020-03-06 19:23 UTC
* [2.3.9] Are you running the latest version?
Version 2.3.9 

**Describe the bug**
You get error message if you click to the search menu item. The searching does not work.

**To Reproduce**
Steps to reproduce the behaviour:
Go to 'search' menu item the you will get an error message. The searching does not work. The playing works well from the recommendations.

[removed]

## Debug log

**Operating System**

Linux CoreELEC 3.14.29 #1 SMP Wed Nov 27 06:02:54 GMT 2019 aarch64 GNU/Linux 

**Additional informatin on the environment**

Beelink Mini MX (2/16GB) - Amlogic S905 CPU

**Comment by NH3CL** [comment] 2020-03-07 13:22
+1

**Comment by arvvoid** [comment] 2020-03-07 20:14
Hello tnx for reporting the issue.
Please don't paste logs directly in messages, attach them as files (like you did) or use a Pastebin like site as per instructions, the later is preferred.
Also, please provide a full debug log (the log you provided has no debug mode enabled in Kodi). Please follow instructions here https://kodi.wiki/view/Log_file/Easy to get proper logs witch includes all details and necessary data to fix the issue faster. Make sure your device doesn't include any banned add-ons (https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons)

**Comment by Klown1985** [comment] 2020-03-08 12:07
Hello!

Ok, I've enabled the debug mode. I upload the needed logs. I hope it will be suitable for you!

Thanks in advance!

Regards,
Klown

[removed]

**Comment by arvvoid** [comment] 2020-03-09 22:45
@Klown1985 Hello, unfortunately, the posted logs are not useful again. In the new logs debugging is enabled but you didn't perform the reported search action with the add-on during the logging.
There are still some banned repositories/add-ons present on your system. 
I will always file and take into consideration a valid, full and confirmed bug report when planning fixes for the next release. 
But I will not provide any direct support if there are banned/piracy add-ons present on the system.

**Comment by Klown1985** [comment] 2020-03-10 08:47
Hello,

I set up the debug mode, then restarted the box, then immediately started the HGO EU addon, then pressed the search menu item and I've just got the error message on the screen. I think the problem can be found in the log:

_2020-03-08 13:02:42.075 T:3973231488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xda' in position 0: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.hbogoeu/main.py", line 25, in <module>
                                                addon_main.router(REQUEST_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.hbogoeu/hbogolib/base.py", line 154, in router
                                                self.handler.searchlist()
                                              File "/storage/.kodi/addons/plugin.video.hbogoeu/hbogolib/handler.py", line 530, in searchlist
                                                self.addCat(self.language(30734), "INTERNAL_SEARCH", self.get_media_resource('search.png'), HbogoConstants.ACTION_SEARCH)
                                              File "/storage/.kodi/addons/plugin.video.hbogoeu/hbogolib/handlereu.py", line 1492, in addCat
                                                'name': name,
                                              File "/usr/lib/python2.7/urllib.py", line 1342, in urlencode
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xda' in position 0: ordinal not in range(128)
                                            -->End of Python script error report<--_

Ok, unfortunatelly I can not delete all add-ons for the debugging, but the problem is also occured on a fresh "virgin" Windows Kodi Leia x64 version, so I think it is not depending on other add-ons. I'm not the only one who experienced this kind of bug. There are many user in 3rd party Kodi forum topics with the same problem. I can upload the Windows version logs If that helps! If not I will wait for new version, might be fix the bug...

Thanks and regards,
Klown

**Comment by arvvoid** [comment] 2020-03-10 09:14
Hello, I saw you updated the log and that one is complete, the bug will be fixed in the next releases. A clean device from banned add-ons and clean log are strongly recommended. 
You are free to use your system as you wish you are responsible for it.
But personally not going to give support to a system containing potentially illegal content since that might make me liable, or potentially erroneously give a bad reputation to a perfectly fine add-on like this, or result in damage and bad press for Kodi. Likewise, no support will be given from any official and legit source for a device containing banned add-ons.

Thanks for the bug report, but it would be more pleasant, quicker and easier, and result in a quicker solution and fix, if the simple rules get followed. https://kodi.wiki/view/Log_file/Easy

**Closed as completed** 2020-03-10 11:01 UTC
Labels: bug, Ignored rules

**Comment by Klown1985** [comment] 2020-03-10 13:45
The searching is also works fine! (2.3.10) Thank you very much! :)
